### PR TITLE
Add Applied property to args of SpicePropertyFound event

### PR DESCRIPTION
**Pull request by marcin-golebiowski**

### CODE REVIEW

**Comment by svenboulanger** [comment]
Why is this necessary?

**Comment by marcin-golebiowski** [comment]
Custom SpicePropertyFound handler is defined BehavioralBiasingBehavior class.

I would like to add support in the parser for over spice properties like Vdb etc. That property will help me ignore the finding if the result is already applied.

**Comment by svenboulanger** [comment]
You can use the check `Result == null` to see if a result hasn't been applied yet (by design).

**Comment by marcin-golebiowski** [comment]
Sure but I would need to cast:

image

However I can live with that.

**Comment by svenboulanger** [comment]
I suggest we review it when Spice# 3.0 is out.

**Comment by marcin-golebiowski** [comment]
Ok. I will provide more feedback about v3.0 today and tomorrow.

**Comment by marcin-golebiowski** [comment]
Sure. No problem :)

**Pull request closed without merging**
