### PR TITLE
Add limit function support

### PR DESCRIPTION
**Pull request by marcin-golebiowski**
PR adds support for LIMIT function that is defined as `limit(x,y,z) = min(max(x,y),z)`

### CODE REVIEW

**Comment by svenboulanger** [comment]
If you look through the comments on the [LTSpice Wiki](http://ltwiki.org/?title=B_sources_%28complete_reference%29), you will find that the description of `limit` is wrong (it is not really `min(max(x,y),z)` but kind of a more complex if-expression).
Please change to the "real" `limit()` behavior.

**Comment by marcin-golebiowski** [comment]
@svenboulanger 


Is following acceptable? Maybe there is a way to minimize it...
I did it according to the comment:
`limit(x,y,z) = x when lo < x < hi, lo when x <= lo, and hi when x >= hi where lo = min(y,z) and hi = max(y,z).`

image

**Comment by svenboulanger** [comment]
Alternative: nested conditionals?

`x < y ? (y < z ? dy : (x < z ? dz : dx)) : (y > z ? dy : (x > z ? dx : dz))`

I actually think a dedicated helper function would be better, because at the moment the arguments will be evaluated multiple times (this is not the case with a dedicated helper function). This might become more problematic if one of these arguments is very long...

**Comment by marcin-golebiowski** [comment]
@svenboulanger  By dedicated you mean "dlimit(0)" "dlimit(1)" "dlimit(2)" functions?

**Comment by svenboulanger** [comment]
Partial derivatives don't really make sense in this case as it's just a bunch of conditions. Maybe just a `DLimit(x,y,z,dx,dy,dz)`?
It does force the derivatives to be computed though...

Argh, difficult :-D

**Comment by marcin-golebiowski** [comment]
@svenboulanger 
Maybe we need a custom RealILState/ComplexILState class where you can optimize usage and evaluation of variables?
Then maybe expression like `x < y ? (y < z ? dy : (x < z ? dz : dx)) : (y > z ? dy : (x > z ? dx : dz))` could be translated to following IL code (pseudo code below):

```
Lazy<double> lx = new Lazy<double>(() => x));
Lazy<double> ly = new Lazy<double>(() => y);
Lazy<double> lz = new Lazy<double>(() => z);

lx.Value < ly.Value ? (ly.Value < lz.Value ? dy ? (lx.Value < lz.Value ? dz: dx)) : (ly.Value > lz.Value ? dy : (lx.Value > lz.Value ? dx : dy))
```

What do you think?

**Comment by svenboulanger** [comment]
I think I see what you mean, but I also think it's not really lazy loading that we need because they're all always used. We basically need a way to store temporary variables in IL. It does make it harder to manage though, which is why I used the helper functions if I needed to do things like that. This is just the peculiar case where half of the arguments need to be evaluated upfront (x, y and z) because they are evaluated multiple times otherwise, and the other half shouldn't be evaluated until needed (dx, dy and dz).

For now, let's go with your first suggestion (where we add conditionals together). I suspect it will not give many problems, and we can leave the optimization for later (premature optimization is the bane of all evil ;-) ).

**Comment by marcin-golebiowski** [comment]
I've changed the logic of Limit.  Please take a look.

**Comment by marcin-golebiowski** [comment]
@svenboulanger Any thoughts about this?

**Comment by svenboulanger** [comment]
Sorry I did not realize you made an update there!
That actually seems like a good solution! 👍

**Pull request merged**
