### PR TITLE
Current through resistor issue

### PR DESCRIPTION
**Pull request by marcin-golebiowski**
There is an issue with I(Resistor) in expressions.
Please find the unit test.

### CODE REVIEW

**Comment by svenboulanger** [comment]
At the moment, this doesn't work by design. A resistor does not define a branch current, so the behavioral source cannot compute derivatives for it...

**Comment by marcin-golebiowski** [comment]
Any plans to change that? I think that could be nice feature.

**Comment by svenboulanger** [comment]
The thing is that I don't know how to go about this correctly. Maybe I could add a optional flag that you can override the 'fully correct' behavior. You will in a lot of cases still get agreeable results, however it is hard to predict what it does for more complex stuff.

I will also take a look how they do it in ngSpice for example.

**Comment by svenboulanger** [comment]
It should be possible with v3.1.

**Pull request closed without merging**
