### PR TITLE
Development

### PR DESCRIPTION
**Pull request by svenboulanger**
- Update to Spice# v2.8.0
- Fixed subcircuit instances for expressions.
- Added I(...) support for current sources as well as voltage sources.

### CODE REVIEW

**Comment by marcin-golebiowski** [comment]
@svenboulanger  Parser is having problem with following expression: " V(in) *  V(in) + 2 "
Message: System.IndexOutOfRangeException

**Comment by svenboulanger** [comment]
Hi @marcin-golebiowski, I can't reproduce the problem. Can you give a small example?

**Comment by marcin-golebiowski** [comment]
In  SpiceSharpBehavioral/SpiceSharpBehavioralTests/Components/BehavioralCurrentSourceTests.cs
change "V(in)*10" to " V(in) +  V(in) + 10 ".

**Comment by svenboulanger** [comment]
Very strange. It runs fine on my setup with that expression. I tried running the expression tree parser and the simple derivatives parser.

**Comment by svenboulanger** [comment]
I stand corrected. It's the space at the end that causes problems. My bad!

**Comment by marcin-golebiowski** [comment]
@svenboulanger Does it support spice properties (e.g. V(1))  as arguments of functions? I'm having problems with that. I'm not sure about that.

**Comment by svenboulanger** [comment]
Not as a literal. When the parser encounters V(1) it will translate it into a Func<double> (+ for each derivative), and the function then decides what to do with that Func<double> but it doesn't know it was V(1).

So if you would write "func(V(1), V(2))", the function wouldn't know the difference with "func(1.5, 3.2)".

What specific usecase do you have in mind?

**Comment by marcin-golebiowski** [comment]
@svenboulanger  I think problem is with parsing expressions like " V(in) + 2" before execution of simulation.

**Comment by svenboulanger** [comment]
You could use a `SimpleParser` to do a quick pass to search for Spice properties. This is how the components search for 'I(...)' in `CreateBehaviors() `.

**Comment by marcin-golebiowski** [comment]
@svenboulanger  Why is V(3, 0) (with space before 0) treated different than V(3,0) ?

**Comment by svenboulanger** [comment]
The reasoning was that I did not want to make any assumptions about the node names. If other behavior is wanted, you could perhaps implement an `IEqualityComparer<string>` that trims spaces from the node names.

**Comment by marcin-golebiowski** [comment]
@svenboulanger 

Something like following needs to be added:

image

**Comment by marcin-golebiowski** [comment]
@svenboulanger 

I think problem with V(3,0) and V(3, 0) is different.

Take a look:
image

**Comment by marcin-golebiowski** [comment]
@svenboulanger There is also more difficult problem. Consider following part of netlist:

image

Behavior for VSENSE1 is created later than Bind for `E_RA	1 4	 VALUE = { V(7,8) * 1K * I(VSENSE1) }`

**Comment by svenboulanger** [comment]
I don't understand what the problem is of having " 0" being different than "0". What if the user wants to use leading spaces in node names?

For the second issue, the behaviors Entity makes sure that `VSENSE1` is created *before* the behavior. This is done here: https://github.com/SpiceSharp/SpiceSharpBehavioral/blob/eaee6c82521907bdfc219975b83b81d7c65901c2/SpiceSharpBehavioral/Components/Common/BehavioralComponent.cs#L56

**Comment by marcin-golebiowski** [comment]
> I don't understand what the problem is of having " 0" being different than "0". What if the user wants to use leading spaces in node names?
> 
> For the second issue, the behavioral Component makes sure that `VSENSE1` is created _before_ the behavioral source. This is done here:
> 
> https://github.com/SpiceSharp/SpiceSharpBehavioral/blob/eaee6c82521907bdfc219975b83b81d7c65901c2/SpiceSharpBehavioral/Components/Common/BehavioralComponent.cs#L56

I think the problem was missing "ToLower()"

image

**Comment by svenboulanger** [comment]
It's supposed to check equality with the `SpicePropertyComparer`... Fixed!

**Comment by marcin-golebiowski** [comment]
> I don't understand what the problem is of having " 0" being different than "0". What if the user wants to use leading spaces in node names?

In Spice#.Parser I think that is a problem because I ignore spaces in many places. It would be inconsistent to have space not ignored in one place.

**Comment by marcin-golebiowski** [comment]
Also it's not possible to have in SPICE netlist node name with space

**Comment by svenboulanger** [comment]
I will add a flag that allows trimming of node names. This still allows node names like "hello world". The user can still force trailing/leading spaces by disabling the `TrimNames` flag on the parser.

**Comment by marcin-golebiowski** [comment]
@svenboulanger  Thank you very much

**Pull request merged**
